apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitea
  name: gitea
spec:
  ports:
  - name: 222-22
    port: 222
    protocol: TCP
    targetPort: 22
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: gitea
  type: NodePort
status:
  loadBalancer: {}      